---
title: "approxProjectors"
author: "Israel Miles, David Orozco"
date: "April 29, 2019"
output: html_document
---

```{r}
# Load libraries
library(tidyverse)
library(ggplot2)
library(lubridate)
library(stringr)
```
```{r}
# Load and prepare data
df <- read.csv("~/Downloads/matrix_data.csv")
df <- df %>% mutate(first4 = str_sub(df$Yday,1,4), last3 = str_pad(str_sub(df$Yday,5), 3, pad = "0")) %>% unite("Yday","first4","last3",sep ="") %>% mutate(ymd = as.Date(Yday,
  format = "%Y%j")) %>% mutate(dayssince = ymd - ymd[1])

## date restructure with multiple formats, turn days since to numeric
df$dayssince <- as.numeric(df$dayssince)
```
```{r}
# Plot ice extent time series
ggplot(data = df, aes(x = dayssince, y = Extent))+
  geom_line(color = "blue")+ ggtitle("Sea Ice Extent(1978-Current)")

ggplot(data = filter(df,dayssince >=10000),aes(x = dayssince, y = Extent))+
  geom_line(color = "blue")+ ggtitle("Sea Ice Extent the last 4745 days")

ggplot(data = filter(df,dayssince >=14000),aes(x = dayssince, y = Extent))+
  geom_line(color = "blue")+ ggtitle("Sea Ice Extent the last 745 days")
```
```{r}
# Create trajectory matrix
Trajectory <- function(data,k) {
  m <- k-1
  traj <- matrix(NA, nrow=m, ncol=k)
  for (i in 1:m) {
    traj[i,] <- data[i:(k+i-1)]
  }
  traj[is.na(traj)] <- 0
  traj
}

# Test that matrix is hankel structure and 9x10 with zeros
list <- seq(1,10, length=10)
testTraj <- Trajectory(list,6)
testTraj
```
```{r}
# Extract original time series from the trajectory matrix
DiagAve <- function(matrix) {
  m <- nrow(matrix)
  k <- ncol(matrix)
  x <- vector(mode="numeric", length=m+k-1)
  for (i in 1:m) {
    diag = 0
    r = i # row start point
    c = 1 # col start point, always left col
    while(r > 0) {
      diag = diag + matrix[r,c]
      r = r - 1
      c = c + 1
    }
    x[i] <- mean(diag/i)
  }
  for (j in 2:k) {
    diag = 0
    r = m
    c = j
    while(c <= k) {
      diag = diag + matrix[r,c]
      r = r - 1
      c = c + 1
    }
    x[m+j-1] <- mean(diag/(k-j+1))
  }
  x
}

# Test that extracted data is 1...10
testDiagAve <- DiagAve(testTraj)
testDiagAve
```
```{r}
# Scale R to B matrix
ScaleRtoB <- function(matrix,lamCut) {
  I <- diag(ncol(matrix))
  norm <- norm(matrix, type="F")
  if(lamCut >= norm/2) {
    B <- matrix/(2*lamCut)
  }
  else {
    B <- (matrix + (norm-2*lamCut)*I)/(2*(norm - lamCut))
  }
  B
}

# Test that function works
R <- testTraj %*% t(testTraj)
lamCut <- norm(R, type="F")*0.05
B <- ScaleRtoB(R,lamCut)
B
```
```{r}
# Iterative procedure to find approximate projector
AproxP <- function(B) {
  Bs <- B %*% B
  aP <- 3*Bs - 2*(Bs %*% B)
  aP
}

# Test that function works
aP <- AproxP(B)
aP

testAproxP <- DiagAve(aP %*% testTraj)
testAproxP
```
```{r}
# Main method

```


